import React,{useEffect,useRef} from 'react';
import {assess,statusLabels,definitions,applicationScope,industryReview} from './industryResearch';
import {MarketEvidence,L} from './MarketEvidence';
import {t as tr,getLanguage} from './i18n';

export function IndustrySummary({s,onOpen}){
 return <button className="industry-summary" onClick={onOpen} aria-label={L('行业应用现状：','Industry adoption: ')+tr(s.name)}><b>{L('行业应用现状','Industry adoption')}</b>{(s.country==='DE'?['de']:['cn','global']).map(region=>{const a=assess(s.id,region);return <span key={region}>{L(region==='de'?'德国':region==='cn'?'中国':'海外',region==='de'?'Germany':region==='cn'?'China':'Overseas')}<strong>{!industryReview(s.id,region)&&s.sourceType==='patent'&&!a.records.length?L('应用待核查','Adoption not yet reviewed'):L(...statusLabels[a.status])}{a.groups.length?L(` · 至少${a.groups.length}家`,` · ${a.groups.length}+ OEMs`):''}</strong></span>;})}</button>;
}
function RegionAssessment({s,region}){
 const a=assess(s.id,region),scope=applicationScope(s),review=industryReview(s.id,region);if(!industryReview(s.id,region)&&s.sourceType==='patent'&&!a.records.length)return <section className="scene-region"><h3>{L(region==='de'?'德国市场':region==='cn'?'中国市场':'海外市场',region==='de'?'Germany':region==='cn'?'China':'Overseas')}</h3><p>{L('应用待核查：该候选目前整理了专利线索，尚未完成量产车型核查，不能据此判断行业没有应用。','Adoption not yet reviewed: patent leads have been reviewed, but production-model research has not been completed. No conclusion about market absence follows.')}</p></section>;
 return <section className="scene-region"><div className="industry-verdicts"><section><span>{L(region==='de'?'德国市场':region==='cn'?'中国市场':'海外市场',region==='de'?'Germany':region==='cn'?'China':'Overseas')}</span><h3>{!industryReview(s.id,region)&&s.sourceType==='patent'&&!a.records.length?L('应用待核查','Adoption not yet reviewed'):L(...statusLabels[a.status])}</h3><p className="adoption-count">{L(`已核实核心应用：至少 ${a.groups.length} 家 OEM`,`Verified core applications: ${a.groups.length}+ OEMs`)}</p><p>{L(`完整匹配 ${a.fullGroups.length} 家；部分核心实现 ${a.partialGroups.length} 家。`,`Full match: ${a.fullGroups.length} OEMs; partial core implementation: ${a.partialGroups.length} OEMs.`)}</p>{a.groups.length>0&&<p>{L('已应用OEM：','Adopting OEMs: ')}{a.groups.map(g=>getLanguage()==='en'?g.en:g.name).join(' / ')}</p>}<p className="helper">{L('计数对象：','Counted application: ')}{L(scope.zh,scope.en)}</p><p className="helper">{L(`另有相关能力 ${a.relatedGroups.length} 家，试点/发布 ${a.pendingGroups.length} 家，均不计入已应用数量。`,`Related capabilities: ${a.relatedGroups.length} OEMs; pilots/announcements: ${a.pendingGroups.length} OEMs. Neither is counted as adoption.`)}</p></section></div>{!!a.historicalGroups.length&&<p className="helper">{L(`历史应用先例 ${a.historicalGroups.length} 家，未计入当前已应用数量。`,`Historical precedents: ${a.historicalGroups.length} OEMs, excluded from current adoption counts.`)}</p>}{a.groups.length>=5&&<p className="helper">{L('该应用已开始跨OEM扩散；此判断限于上方计数对象，不能推断全场景或所有车型已经普及。','This application is spreading across OEMs. The assessment applies to the counted application, not the full scenario or every model.')}</p>}{review&&<div className="industry-review"><p>{L(review.note,review.noteEn)}</p><small>{L("核查日期：","Reviewed: ")}{review.checkedAt||"2026-10-07"}</small>{review.sources.map((url,i)=><p key={url}><a href={url} target="_blank" rel="noopener noreferrer">{L("背景与核查资料 ","Context / reviewed reference ")}{i+1} ↗</a></p>)}</div>}<MarketEvidence records={a.records}/>{!!review?.benchmarks?.length&&<section className="industry-reference"><h4>{L("本地服务与设备参考（不计入OEM数量）","Local services and equipment (excluded from OEM counts)")}</h4>{review.benchmarks.map(r=><div key={r.url}><b>{L(r.name,r.en.name)}</b><p>{L(r.feature,r.en.feature)}</p><p className="helper">{L(r.boundary,r.en.boundary)}</p><a href={r.url} target="_blank" rel="noopener noreferrer">{L("查看来源","View source")} ↗</a></div>)}</section>}</section>;
}
export function IndustryDialog({s,onClose}){
 const ref=useRef();useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);
 return <dialog className="modal industry-modal" ref={ref} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><header><div><span className="eyebrow">BEESCENE / 2026-10-07</span><h2>{L('行业应用现状','Industry adoption')} · {tr(s.name)}</h2></div><button className="button" onClick={onClose}>{L('关闭','Close')}</button></header><p className="helper">{s.country==='DE'?<>{L('针对德国市场核查本场景；历史车型先例与现款可用性分别说明。数量为官方证据下限，不是装车率；本地手机服务和设备不计入OEM数量。','This scenario is reviewed for Germany, distinguishing historical models from current availability. Counts are documented lower bounds, not installation rates; services and equipment are excluded.')}</>:L('围绕本场景分别核查中外应用。数量是本次已找到官方证据的OEM下限，按集团去重，不是市场总量或装车率；部分实现不等于完整AI流程。','China and overseas are assessed for this scenario. Counts are verified lower bounds, deduplicated by OEM group—not market totals or penetration rates. Partial implementation does not prove the full AI workflow.')}</p>{(s.country==='DE'?['de']:['cn','global']).map(region=><RegionAssessment key={region} s={s} region={region}/>)}<details className="industry-method"><summary>{L('数量判断口径与资料边界','Count criteria and limitations')}</summary>{definitions.map(([zh,text,en,et])=><p key={zh}><b>{L(zh,en)}</b> · {L(text,et)}</p>)}<p>{L('各地区、年款、配置与OTA条件分别核对。未找到证据不代表不存在；空白场景仍需继续核查。','Region, model year, configuration and OTA conditions remain relevant. Missing evidence is not proof of absence; gaps require further research.')}</p></details></dialog>;
}
