import {t as tr} from './i18n';
import React,{useEffect,useRef,useState} from 'react';
import {Cross2Icon,DownloadIcon,PlusIcon} from '@radix-ui/react-icons';
import {investmentCards} from './investmentCards';
import {dimensions,evidenceTypes,evidenceKey,parseEvidence,validateDraft,latestEvidence,briefCases} from './decisionEvidence';
function boot(){try{return {records:parseEvidence(localStorage.getItem(evidenceKey)),error:''};}catch{return {records:[],error:'证据读取失败，原有存储未覆盖。请检查浏览器存储或已有备份。'};}}
function fresh(){return {dimension:'acceptance',type:'用户调研',date:new Date().toLocaleDateString('en-CA'),scope:'',source:'',finding:'',direction:'尚不能判断',judgment:'待验证',link:''};}
export default function InvestmentDetail({s,onClose}){
 const ref=useRef(),[initial]=useState(boot),[records,setRecords]=useState(initial.records),[error,setError]=useState(initial.error),[adding,setAdding]=useState(false),[draft,setDraft]=useState(fresh),[notice,setNotice]=useState(''),[removing,setRemoving]=useState(null);const d=investmentCards[s.id],items=records.filter(e=>e.sceneId===s.id);
 useEffect(()=>{const el=ref.current;el.showModal();return()=>{if(el.open)el.close();};},[]);
 function edit(k,v){setDraft(x=>({...x,[k]:v}));}
 function save(e){e.preventDefault();const invalid=validateDraft(draft);if(invalid){setError(invalid);return;}try{const existing=parseEvidence(localStorage.getItem(evidenceKey));const next=[...existing,{...draft,id:crypto.randomUUID(),sceneId:s.id,createdAt:new Date().toISOString()}];localStorage.setItem(evidenceKey,JSON.stringify(next));setRecords(next);setError('');setNotice('证据已保存在此浏览器，可导出备份。');setDraft(fresh());setAdding(false);}catch{setError('保存失败，记录尚未保存。请检查浏览器存储并重试。');}}
 function removeRecord(id){try{const next=parseEvidence(localStorage.getItem(evidenceKey)).filter(e=>e.id!==id);localStorage.setItem(evidenceKey,JSON.stringify(next));setRecords(next);setRemoving(null);setError('');setNotice('已删除此条记录。');}catch{setError('删除失败，原记录仍保留。');}}
 function exportCard(){const payload={schemaVersion:'decision-evidence-1',sceneId:s.id,sceneName:s.name,initialHypotheses:briefCases[s.id],researchPlan:d,evidence:items,exportedAt:new Date().toISOString()};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${s.id}-${s.name}-决策与证据.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <dialog ref={ref} className="modal investment-modal" aria-labelledby="investment-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}>
 <header><div><span className="eyebrow">TOP {tr(String(s.rank).padStart(3,'0'))}{tr(" · 决策卡 v0.2.1")}</span><h2 id="investment-title">{tr(s.name)}{tr(" · 投资决策卡")}</h2></div><button className="icon-button" aria-label={tr("关闭投资决策卡")} onClick={onClose}><Cross2Icon/></button></header>
 <div className="decision-context"><span>{tr(d.role)} · {tr(d.decision)}</span><p>{tr(d.product)}</p><small>{tr("车型定位、价位、目标人群及部署方式是项目输入，尚未指定；以下为研究问题与候选实现思路，不构成产品适配或投入结论。")}</small></div>
 {error&&<p className="evidence-error" role="alert">{tr(error)}</p>}{notice&&<p className="evidence-notice" role="status">{tr(notice)}</p>}
 <div className="decision-six">{dimensions.map(([id,name])=>{const last=latestEvidence(records,s.id,id),count=items.filter(e=>e.dimension===id).length;return <section key={id}><header><h3>{tr(name)}</h3><span>{tr(last?last.judgment:'待验证')}</span></header><p>{tr(briefCases[s.id][id])}</p><small>{tr(last?`最新录入判断 · ${last.type} · ${last.date}`:'初步假设 · 无已录入证据')}</small>{last&&<p className="decision-latest">{tr(last.finding)}<small>{tr("适用：")}{tr(last.scope)} · {tr(count)}{tr("条记录；完整历史见下方")}</small></p>}</section>;})}</div>
 <section className="evidence-section"><div className="evidence-heading"><div><h3>{tr("证据与历史 ")}<span>{tr(items.length)}</span></h3><p>{tr("按来源和适用条件积累，支持与反驳都保留。")}</p></div><button className="button primary" onClick={()=>{setAdding(!adding);setNotice('');}} aria-expanded={adding}><PlusIcon/>{tr(adding?'收起表单':'补充证据')}</button></div>
 {adding&&<form className="evidence-form" onSubmit={save}>
 <div className="evidence-form-grid"><label>{tr("判断维度")}<select value={draft.dimension} onChange={e=>edit('dimension',e.target.value)}>{dimensions.map(([id,name])=><option key={id} value={id}>{tr(name)}</option>)}</select></label><label>{tr("证据类型")}<select value={draft.type} onChange={e=>edit('type',e.target.value)}>{evidenceTypes.map(t=><option key={t} value={t}>{tr(t)}</option>)}</select></label><label>{tr("记录日期")}<input type="date" required value={draft.date} onChange={e=>edit('date',e.target.value)}/></label><label>{tr("来源／记录者")}<input required value={draft.source} onChange={e=>edit('source',e.target.value)} placeholder={tr("访谈编号、研究者或演示记录")}/></label><label className="wide">{tr("适用条件")}<input required value={draft.scope} onChange={e=>edit('scope',e.target.value)} placeholder={tr("用户、车型、模型／硬件版本、场景与样本范围")}/></label><label>{tr("对初步假设的方向")}<select value={draft.direction} onChange={e=>edit('direction',e.target.value)}>{['尚不能判断','支持','反驳','混合'].map(t=><option key={t} value={t}>{tr(t)}</option>)}</select></label><label>{tr("本条记录的判断")}<select value={draft.judgment} onChange={e=>edit('judgment',e.target.value)}>{['待验证','正向','有限／有条件','负向'].map(t=><option key={t} value={t}>{tr(t)}</option>)}</select></label><label className="wide">{tr("观察结果与依据")}<textarea required rows={3} value={draft.finding} onChange={e=>edit('finding',e.target.value)} placeholder={tr("记录行为、测量或原话，说明结论与限制；模型规模可填写在此处")}/></label><label className="wide">{tr("资料链接（可选）")}<input type="url" value={draft.link} onChange={e=>edit('link',e.target.value)} placeholder={tr("https://… 访谈、视频或测量报告")}/></label></div><p className="helper">{tr("一次记录对应一个维度。最新录入判断仅代表该条记录，不覆盖旧证据，也不自动成为最终结论。")}</p><div className="modal-actions"><button type="submit" className="button primary">{tr("保存证据")}</button><button type="button" className="button" onClick={()=>setAdding(false)}>{tr("取消")}</button></div></form>}
 {!items.length?<p className="evidence-empty">{tr("还没有录入证据。可从用户调研、专家访谈或实车演示开始；初步假设不计入证据数量。")}</p>:<ol className="evidence-history">{[...items].reverse().map(e=><li key={e.id}><header><b>{tr(dimensions.find(([id])=>id===e.dimension)[1])} · {tr(e.type)}</b><span>{tr(e.direction)} · {tr(e.judgment)}</span></header><p>{e.finding}</p><small>{tr(e.date)}{tr(" · 来源：")}{e.source}<br/>{tr("适用：")}{e.scope}</small>{e.link&&/^https?:\/\//i.test(e.link)&&<a href={e.link} target="_blank" rel="noopener noreferrer">{tr("查看资料 ↗")}</a>}<div className="evidence-remove">{removing===e.id?<><span>{tr("确认删除这条记录？")}</span><button className="text-button" onClick={()=>removeRecord(e.id)}>{tr("确认删除")}</button><button className="text-button" onClick={()=>setRemoving(null)}>{tr("保留")}</button></>:<button className="text-button" onClick={()=>setRemoving(e.id)}>{tr("删除记录")}</button>}</div></li>)}</ol>}
 <p className="evidence-local">{tr("记录仅保存在此浏览器，尚未接入共享数据库或CyberEdge；可导出当前场景的全部证据与研究计划备份。")}</p></section>
 <details className="decision-research"><summary>{tr("展开参考研究计划与条件判断")}</summary><div className="investment-panel"><p>{tr(d.audience)}</p><h3 className="investment-section-title">{tr("与什么比较")}</h3><p>{tr(d.baseline)}</p><h3 className="investment-section-title">{tr("分阶段验证")}</h3>{d.experiment.map(e=><section className="investment-experiment" key={e.stage}><h4>{tr(e.stage)}</h4><div><p>{tr(e.method)}</p><p>{tr(e.output)}</p></div></section>)}<h3 className="investment-section-title">{tr("供具体项目验证的条件判断")}</h3>{d.gates.map(g=><p key={g.label}><b>{tr(g.label)}：</b>{tr(g.text)}</p>)}<p className="investment-footnote">{tr(d.capability)}<br/>{tr(d.costs)}</p></div></details>
 <div className="modal-actions"><button className="button" onClick={exportCard}><DownloadIcon/>{tr("导出决策与证据")}</button><button className="button" onClick={onClose}>{tr("返回场景库")}</button></div></dialog>;
}
