import React,{useEffect,useRef} from 'react';
import {ReaderIcon,ArrowTopRightIcon} from '@radix-ui/react-icons';
import {L} from './MarketEvidence';
import {t as tr,getLanguage} from './i18n';
import {patentsFor,domainLabels,domainDefinitions,scenarios} from './scenarios';

export function DomainBadge({s}){return <span className={`domain-badge ${s.sceneDomain}`}>{L(...domainLabels[s.sceneDomain])}</span>}
export function DomainAnalysis({s}){return <section className="detail-block"><h3>{L('场景领域分析','Scenario domain analysis')}</h3><DomainBadge s={s}/><p>{s.domainReasonEn?L(s.domainReason,s.domainReasonEn):tr(s.domainReason)}</p><p className="helper">{L(...domainDefinitions[s.sceneDomain])}</p></section>}
export function PatentBadge({s,onOpen}){
 const rows=patentsFor(s.id);if(!rows.length)return null;
 return <button className="patent-badge" onClick={onOpen} aria-label={L('查看相关专利：','View related patents: ')+tr(s.name)}><ReaderIcon/><b>{L('相关专利','Related patents')}</b><span>{rows.length}</span><ArrowTopRightIcon/></button>;
}
export function PatentDialog({s,onClose,onScene}){
 const ref=useRef();useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);
 const rows=patentsFor(s.id),english=getLanguage()==='en';
 return <dialog ref={ref} className="modal patent-modal" aria-labelledby="patent-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><header><div><span className="eyebrow">BEESCENE / PATENT RESEARCH · 2026-10-07</span><h2 id="patent-title">{L('相关专利','Related patents')} · {tr(s.name)}</h2></div><button className="button" onClick={onClose}>{L('关闭','Close')}</button></header><p className="patent-context">{L('这里展示与场景机制相关的公开专利文本。专利不代表车型已应用，也不证明完整场景实现。技术主题与关联范围为阅读分析，法律有效性及权利覆盖未作判定。','These published patent texts relate to scenario mechanisms. A patent does not establish model availability or a complete implementation. Topics and relationships are analyst interpretations; legal validity and claim coverage have not been determined.')}</p><DomainBadge s={s}/>{rows.map(p=>{const v=english?p.en:p;return <article className="patent-record" key={p.number}><div className="patent-record-top"><span className="patent-number">{p.number}</span><span>{L(p.documentType==='grant'?'授权公告文本':'申请公开文本',p.documentType==='grant'?'Granted patent text':'Published application')}</span></div><h3>{v.title}</h3><dl className="patent-meta"><dt>{L('申请人','Applicant')}</dt><dd>{v.applicant}</dd><dt>{L('申请日','Filing date')}</dt><dd>{p.filingDate}</dd><dt>{L(p.documentType==='grant'?'授权公告日':'公开日',p.documentType==='grant'?'Grant publication':'Publication date')}</dt><dd>{p.publicationDate}</dd><dt>{L('发现来源','Discovery')}</dt><dd>{L(p.discovery==='report'?'报告线索 + 专利文本核对':'行业检索 + 专利文本核对',p.discovery==='report'?'Report lead + patent text review':'Industry search + patent text review')}</dd></dl><p>{v.summary}</p><div className="patent-match"><b>{L('与本场景的关联及边界','Relationship and limits')}</b><p>{v.scope}</p></div><a className="button" href={p.source} target="_blank" rel="noopener noreferrer">{L('阅读公开专利文本','Read published patent text')}<ArrowTopRightIcon/></a><details className="patent-related"><summary>{L('该专利关联的其他场景','Other scenarios related to this patent')}</summary><div>{p.sceneIds.filter(id=>id!==s.id).map(id=>{const related=scenarios.find(x=>x.id===id);return related&&<button className="text-button" key={id} onClick={()=>onScene(related)}>{tr(related.name)}<ArrowTopRightIcon/></button>;})}</div></details></article>;})}<p className="helper">{L('本次按场景检索并核对摘要及相关权利要求；尚未穷尽全部专利或同族。申请公开与授权公告分别标记，同一条记录只计一次，不纳入行业应用OEM数量。','This review checked abstracts and relevant claims per scenario; it is not exhaustive across patents or families. Published applications and grants are distinct; each record is counted once and excluded from industry adoption OEM counts.')}</p></dialog>;
}
