import React,{useState,useEffect,useRef} from 'react';
import {needDimensions,aiDimensions,vehicleDimensions} from './top100';
import {t as tr,getLanguage} from './i18n';
import {L,MarketEvidence} from './MarketEvidence';
const apiRoot=import.meta.env.VITE_API_BASE||`${import.meta.env.BASE_URL==='./'?'/':import.meta.env.BASE_URL}api/`;
async function api(path,method='GET',body){const r=await fetch(apiRoot+path,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json();}catch{throw Error(L('后台尚未连接，当前页面只能浏览公共场景。','Backend unavailable. Public scenarios remain browsable.'));}if(!r.ok)throw Error(data.error||'Request failed');return data;}
const fields={name:['场景名称','Scenario name'],summary:['场景描述','Scenario description'],outcome:['预期收益','Expected benefit'],baseline:['现有替代','Existing alternative'],question:['验证问题','Validation question'],horizon:['研究窗口','Research horizon'],autonomyMode:['自主程度','Autonomy']};
const blank=()=>({name:'',summary:'',outcome:'',baseline:'',question:'',horizon:'近期试验',autonomyMode:'用户发起或确认后推进',primaryNeed:'ease',secondaryNeed:null,ai:['intent'],vehicle:['space'],tags:[],interaction:[],en:{},market:[]});

const emptyClaim=()=>({brand:'',model:'',region:'',feature:'',boundary:'',source:'',status:'unverified',match:'partial'});
export default function PersonalWorkspace({onClose}){
 const dialog=useRef(),[user,setUser]=useState(null),[ready,setReady]=useState(false),[enabled,setEnabled]=useState(false),[online,setOnline]=useState(false),[rows,setRows]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('login'),[credentials,setCredentials]=useState({username:'',password:''}),[draft,setDraft]=useState(null),[editing,setEditing]=useState(null),[baseId,setBaseId]=useState(null),[description,setDescription]=useState(''),[readOnly,setReadOnly]=useState(false),[filter,setFilter]=useState('');
 const refresh=async(u)=>{if(u){const data=await api('scenes');setRows(data.scenes);return data.scenes;}setRows([]);return [];};
 const edit=(s,row=null)=>{setDraft(structuredClone(s));setEditing(row);setBaseId(row?.baseId||null);setReadOnly(!!row&&(row.ownerId!==user?.id||!!row.baseId));setError('');setNotice('');};
 useEffect(()=>{dialog.current.showModal();let live=true;(async()=>{try{const session=await api('session');if(!live)return;setOnline(true);setUser(session.user);setEnabled(session.generationEnabled);await refresh(session.user);}catch(e){if(live)setError(e.message);}finally{if(live)setReady(true);}})();return()=>{live=false;dialog.current?.close();};},[]);
 async function authenticate(e){e.preventDefault();setBusy(true);setError('');try{const {user:u}=await api(mode,'POST',credentials);setCredentials({username:'',password:''});setUser(u);await refresh(u);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const result=await api(editing?'scenes/'+editing.id:'scenes',editing?'PUT':'POST',{scene:draft,baseId,revision:editing?.revision});const data=await refresh(user),row=data.find(r=>r.id===result.id);setEditing(row);setDraft(row.scene);setNotice(L('已保存到后台。仅你和管理员可见。','Saved to the backend. Visible only to you and administrators.'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function createWithAI(){setBusy(true);setError('');try{const {scene}=await api('generate','POST',{description});setDraft(scene);setEditing(null);setBaseId(null);setReadOnly(false);setNotice(L('已生成草稿，请核对后保存。市场信息需单独添加证据。','Draft generated. Review and save it; add market evidence separately.'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 const change=(k,v)=>setDraft(d=>({...d,[k]:v}));
 const claim=(i,k,v)=>setDraft(d=>({...d,market:d.market.map((c,j)=>i===j?{...c,[k]:v,en:undefined}:c)}));
 return <dialog className="modal personal-modal" ref={dialog} onCancel={e=>{e.preventDefault();onClose();}}><header><div><span className="eyebrow">BEESCENE / {L('个人工作区','PERSONAL WORKSPACE')}</span><h2>{L(user?.role==='admin'?'全部用户场景':'我的场景',user?.role==='admin'?'All user scenarios':'My scenarios')}</h2></div><button className="button" onClick={onClose}>{L('关闭','Close')}</button></header>
 <p className="helper">{L('现有公共场景不可修改。你可以单独新增场景，仅本人和管理员可见。','Existing public scenarios cannot be modified. Add your own scenarios, visible only to you and administrators.')}</p>
 {error&&<p className="workspace-error" role="alert">{error}</p>}{notice&&<p className="workspace-notice" role="status">{notice}</p>}
 {!ready?<p>{L('正在连接后台…','Connecting…')}</p>:!online?<p>{L('注册、保存和生成需要网站后台。GitHub Pages仅提供公共库浏览。','Registration, saving and generation require a backend. GitHub Pages serves the public library.')}</p>:!user?<form onSubmit={authenticate} className="account-form"><h3>{L(mode==='register'?'注册账户':'登录账户',mode==='register'?'Create account':'Sign in')}</h3><label>{L('用户名','Username')}<input required autoComplete="username" value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})}/></label><label>{L('密码（至少10位）','Password (10+ characters)')}<input type="password" required minLength={10} autoComplete={mode==='register'?'new-password':'current-password'} value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/></label><button className="button primary" disabled={busy}>{L(mode==='register'?'注册并登录':'登录',mode==='register'?'Register and sign in':'Sign in')}</button><button type="button" className="text-button" onClick={()=>setMode(mode==='register'?'login':'register')}>{L(mode==='register'?'已有账户，去登录':'没有账户，注册',mode==='register'?'Already registered? Sign in':'Create an account')}</button></form>:<>
 <div className="workspace-controls"><span>{user.username} · {L(user.role==='admin'?'管理员':'注册用户',user.role==='admin'?'Administrator':'Registered user')}</span><button className="button" onClick={()=>{edit(blank());setBaseId(null);}}>{L('添加自定义场景','Add custom scenario')}</button><button className="text-button" onClick={async()=>{try{await api('logout','POST',{});setUser(null);setRows([]);setDraft(null);}catch(e){setError(e.message);}}}>{L('退出登录','Sign out')}</button></div>
 <label className="workspace-search">{L('搜索个人场景 / 用户','Search private scenarios / users')}<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><div className="private-list">{rows.filter(r=>(r.scene.name+' '+r.owner).toLowerCase().includes(filter.toLowerCase())).map(r=><button className="private-row" key={r.id} onClick={()=>edit(r.scene,r)}><strong>{getLanguage()==='en'?(r.scene.en?.name||r.scene.name):r.scene.name}</strong><small>{r.owner} · {r.baseId||L('自定义','Custom')} · v{r.revision} · {L(r.ownerId===user.id&&!r.baseId?'编辑':'查看',r.ownerId===user.id&&!r.baseId?'Edit':'View')}</small></button>)}{!rows.length&&<p className="helper">{L('暂无个人场景。点击添加自定义场景开始。','No private scenarios yet. Add a custom scenario to start.')}</p>}</div>
 {draft&&<form onSubmit={save} className="scenario-editor"><h3>{L(readOnly?'查看用户场景':editing?'编辑自定义场景':'新建个人场景',readOnly?'View user scenario':editing?'Edit private version':'New private scenario')}</h3>{baseId&&<p className="helper">{L('基础场景：','Based on: ')}{baseId}</p>}
 {!readOnly&&<section className="generation-box"><label>{L('描述你的场景，让GPT补齐模板','Describe your scenario; let GPT complete the template')}<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={L('谁在什么情况下，需要车辆和AI一起完成什么？','Who needs the vehicle and AI to do what, and when?')}/></label><button type="button" className="button" disabled={busy||!enabled||description.trim().length<8} onClick={createWithAI}>{busy?L('处理中…','Working…'):L('一键生成草稿','Generate draft')}</button>{!enabled&&<p className="helper">{L('管理员配置服务器API Key和模型后启用。现在可手工填写并保存。','Enabled after the administrator configures a server API key and model. Manual editing is available.')}</p>}</section>}
 <fieldset disabled={readOnly||busy}>{Object.entries(fields).map(([k,label])=><label key={k}>{L(...label)}{k==='horizon'?<select value={draft[k]} onChange={e=>change(k,e.target.value)}>{['近期试验','条件预研','前瞻探索'].map(x=><option value={x} key={x}>{tr(x)}</option>)}</select>:<textarea required value={draft[k]} onChange={e=>change(k,e.target.value)} rows={k==='name'?1:2}/>}</label>)}
 <div className="dimension-fields">{[['primaryNeed','主需求','Primary need'],['secondaryNeed','次需求','Secondary need']].map(([k,zh,en])=><label key={k}>{L(zh,en)}<select value={draft[k]||''} onChange={e=>change(k,e.target.value||null)}>{k==='secondaryNeed'&&<option value="">{L('无','None')}</option>}{Object.entries(needDimensions).map(([id,n])=><option key={id} value={id}>{tr(n)}</option>)}</select></label>)}</div>
 {[['ai',aiDimensions,'AI能力','AI capabilities'],['vehicle',vehicleDimensions,'车用理由','Vehicle fit']].map(([key,labels,zh,en])=><section key={key}><b>{L(zh,en)}</b><div className="editor-checks">{Object.entries(labels).map(([id,n])=><label key={id}><input type="checkbox" checked={draft[key].includes(id)} onChange={e=>change(key,e.target.checked?[...draft[key],id]:draft[key].filter(x=>x!==id))}/>{tr(n)}</label>)}</div></section>)}
 <label>{L('HAI交互流程（每行一步）','HAI interaction flow (one step per line)')}<textarea rows={5} value={draft.interaction.join('\n')} onChange={e=>change('interaction',e.target.value.split('\n'))}/></label>
 <details><summary>{L('英文版本（可人工修改）','English version (editable)')}</summary>{Object.entries(fields).map(([k,label])=><label key={k}>{label[1]}<textarea value={draft.en?.[k]||''} onChange={e=>change('en',{...draft.en,[k]:e.target.value})}/></label>)}</details>
 <h3>{L('品牌车型与行业应用记录','Brands, models and industry records')}</h3>{draft.market.map((c,i)=><section className="claim-editor" key={i}>{[['brand','品牌','Brand'],['model','车型 / 年款','Model / model year'],['region','市场 / 配置条件','Market / conditions'],['feature','已提供功能','Available feature'],['boundary','匹配范围及缺口','Match and gaps'],['source','来源链接','Source URL']].map(([k,zh,en])=><label key={k}>{L(zh,en)}<input value={c[k]} required={['brand','model'].includes(k)} onChange={e=>claim(i,k,e.target.value)}/></label>)}<label>{L('证据状态','Evidence status')}<select value={c.status} onChange={e=>claim(i,'status',e.target.value)}><option value="unverified">{L('待核实','Unverified')}</option><option value="provided">{L('已提供（人工标注）','Available (manual assertion)')}</option><option value="announced">{L('官方发布','Announced')}</option></select></label><label>{L('匹配程度','Match')}<select value={c.match} onChange={e=>claim(i,'match',e.target.value)}><option value="partial">{L('部分匹配','Partial')}</option><option value="related">{L('相关能力','Related')}</option><option value="full">{L('完整匹配','Full')}</option></select></label><button type="button" className="text-button" onClick={()=>change('market',draft.market.filter((_,j)=>j!==i))}>{L('移除此记录','Remove record')}</button></section>)}<button type="button" className="button" onClick={()=>change('market',[...draft.market,emptyClaim()])}>{L('添加品牌车型','Add brand/model')}</button></fieldset>
 {readOnly?<MarketEvidence records={draft.market}/>:<div className="editor-actions"><button className="button primary" disabled={busy}>{L('保存个人场景','Save private scenario')}</button><span className="helper">{L('仅本人和管理员可见','Visible to you and administrators only')}</span></div>}</form>}
 </>}
 </dialog>;
}
